FROM maven:3.9.9-amazoncorretto-21-alpine AS build
COPY . /app
WORKDIR /app
RUN mvn clean package

FROM amazoncorretto:21-alpine
COPY --from=build /app/app/target/*.jar /app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]
